paths:
  high: []
  low:
    - "**"
modules:
  medium_from: 99
  high_from: 99
size:
  low:
    lines_under: 999999
    files_up_to: 999999
  medium:
    lines_under: 999999
    files_up_to: 999999
tests:
  files: []
